from django.urls import path
from.import views

urlpatterns=[
    path('customerhome/',views.customerhome,name="customerhome"),
    path('logout/',views.logout,name="logout"),
    path('response/',views.response,name="response"),
    path('viewprofile/',views.viewprofile,name="viewprofile"),
    path('products/',views.products,name="products"),
    path('',views.dashboard,name='dashboard'),
    path('dogs/',views.dogs,name='dogs'),
    path('food/',views.food,name='food'),
    path('food1/',views.food1,name='food1'),
    path('food2/',views.food2,name='food2'),
    path('food3/',views.food3,name='food3'),
    path('food4/',views.food4,name='food4'),
    path('food5/',views.food5,name='food5'),
    path('food6/',views.food6,name='food6'),
    path('food7/',views.food7,name='food7'),
    path('kid/',views.kid,name='kid'),
    path('kid1/',views.kid1,name='kid1'),
    path('kid2/',views.kid2,name='kid2'),
    path('kid3/',views.kid3,name='kid3'),
    path('kid4/',views.kid4,name='kid4'),
    path('kid5/',views.kid5,name='kid5'),
    path('kid6/',views.kid6,name='kid6'),
    path('kid7/',views.kid7,name='kid7'),

    path('dfood/',views.dfood,name='dfood'),
    path('dfood1/',views.dfood1,name='dfood1'),
    path('dfood2/',views.dfood2,name='dfood2'),
    path('dfood3/',views.dfood3,name='dfood3'),
    path('dfood4/',views.dfood4,name='dfood4'),
    path('dfood5/',views.dfood5,name='dfood5'),
    path('dkid/',views.dkid,name='dkid'),
    path('dkid1/',views.dkid1,name='dkid1'),
    path('dkid2/',views.dkid2,name='dkid2'),
    path('dkid3/',views.dkid3,name='dkid3'),
    path('dkid4/',views.dkid4,name='dkid4'),
    path('dkid5/',views.dkid5,name='dkid5'),
    path('dkid6/',views.dkid6,name='dkid6'),
    path('dkid7/',views.dkid7,name='dkid7'),
    path('dkid8/',views.dkid8,name='dkid8'),
    path('dkid9/',views.dkid9,name='dkid9'),
]