# Generated by Django 5.0.4 on 2024-05-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='responetext',
            new_name='responsetext',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='Responsetype',
            new_name='responsetype',
        ),
    ]
